remote_theme: pages-themes/time-machine@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: [Tejas Tipare]
description: [Iâ€™m an Azure Data Engineer passionate about building modern data platforms using Microsoft Fabric and Databricks. Explore my projects, blogs, and data architecture designs.]
